version: 0.2

phases:
  install:
    runtime-versions:
     
      java: corretto21
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Spring Boot application..."
      - mvn clean install
      - mv target/*.jar javaapp.jar
      - echo "Build completed on `date`"
      - echo "Starting the application..."
      - nohup java -jar javaapp.jar > app.log 2>&1 &
      - echo $! > app.pid
      - sleep 10 # Allow the application to start
      - echo "Checking if the application is running..."
      - curl -f http://localhost:5000 || { echo "Application failed to start"; exit 1; }
      - echo ls -a

  post_build:
    commands:
      - echo "Running OWASP ZAP container..."
      - docker pull zaproxy/zap-stable
      - docker image ls 
      - curl -f http://localhost:5000 || { echo "Application failed to start"; exit 1; }
      - echo "Starting ZAP scan against the application..."
      - docker run -v $(pwd):/zap/wrk/:rw --network="host" -t zaproxy/zap-stable zap-baseline.py -t http://localhost:5000 -r report.html
      - echo "OWASP ZAP scan completed."
      - echo netstat -tulpn
      - echo "Stopping the application..."
      - kill -9 $(cat app.pid) || echo "Application already stopped"

artifacts:
  files:
    - javaapp.jar
    - app.log
    - zap_report.html
