version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Spring Boot application...
      - mvn clean package # This assumes you're using Maven wrapper (mvnw)
      - echo Build completed on `date`

  post_build:
        commands:
          - echo post_build
          - mv target/*.jar javaapp.jar

artifacts:
  files:
    - javaapp.jar

